global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Qayd POS Application
  - job_name: 'qayd-pos'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node.js application metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  # ZATCA API monitoring
  - job_name: 'zatca-api'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/zatca/metrics'
    scrape_interval: 60s

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/health'
    scrape_interval: 30s

