apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qayd-pos.fullname" . }}-secrets
  labels:
    {{- include "qayd-pos.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc }}
  {{- end }}
  {{- if .Values.secrets.zatcaCertPfx }}
  zatca-cert-pfx: {{ .Values.secrets.zatcaCertPfx | b64enc }}
  {{- end }}
  {{- if .Values.secrets.zatcaCertPassword }}
  zatca-cert-password: {{ .Values.secrets.zatcaCertPassword | b64enc }}
  {{- end }}
  {{- if .Values.secrets.firebaseApiKey }}
  firebase-api-key: {{ .Values.secrets.firebaseApiKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.firebaseAuthDomain }}
  firebase-auth-domain: {{ .Values.secrets.firebaseAuthDomain | b64enc }}
  {{- end }}
  {{- if .Values.secrets.firebaseProjectId }}
  firebase-project-id: {{ .Values.secrets.firebaseProjectId | b64enc }}
  {{- end }}

