# Default values for qayd-pos
replicaCount: 3

image:
  repository: qayd-pos
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: qayd-pos.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: qayd-pos-tls
      hosts:
        - qayd-pos.example.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables
env:
  NODE_ENV: "production"
  PORT: "3000"

# Secrets
secrets:
  databaseUrl: ""
  zatcaCertPfx: ""
  zatcaCertPassword: ""
  firebaseApiKey: ""
  firebaseAuthDomain: ""
  firebaseProjectId: ""

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "qayd_password"
    username: "qayd_user"
    password: "qayd_password"
    database: "qayd_pos"
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: ""

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: ""

# Monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s

# Logging
logging:
  level: "info"
  format: "json"

# Health checks
healthCheck:
  enabled: true
  path: "/health"
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Backup
backup:
  enabled: true
  schedule: "0 2 * * *"
  retention: "30d"
  storage:
    size: "10Gi"
    storageClass: ""

# Security
security:
  podSecurityPolicy:
    enabled: false
  networkPolicy:
    enabled: false
  serviceAccount:
    create: true
    name: "qayd-pos"

# Development
dev:
  enabled: false
  hotReload: false
  debugMode: false

